version: "3.8"
services:
  postgresql:
    image: postgres:latest
    restart: on-failure
    container_name: flight-application-postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flightReservation
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flight-application-network

networks:
  flight-application-network:

volumes:
  postgres-data:
    driver: local