spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flightReservation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
  application:
    name: ReservationService

server:
  port: 8080